name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: composer install
      run: docker-compose run --rm ecs_laravel_app composer install

    - name: cp env
      run: cp .env.example .env

    - name: start project
      run: docker-compose up -d

    # dbの起動完了までにmigrationが走らないように
    - name: sleep
      run: sleep 10

    - name: key generate
      run: docker-compose run --rm ecs_laravel_app php artisan key:generate

    - name: migrate
      run: docker-compose run --rm ecs_laravel_app php artisan migrate

    - name: test
      run: docker-compose run --rm ecs_laravel_app ./vendor/bin/phpunit