name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  unit-test:
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: composer install
        uses: docker-compose run --rm ecs_laravel_app composer install

      - name: cp env
        uses: cp .env.example .env

      - name: key generate
        uses: docker-compose run --rm ecs_laravel_app php artisan key:generate

      - name: migrate
        uses: docker-compose run --rm ecs_laravel_app php artisan migrate

      - name: test
        uses: docker-compose run --rm ecs_laravel_app ./vendor/bin/phpunit